services:
    db:
        image: postgres:16.4
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - coffeshop_postgres_data:/var/lib/postgresql/data/
        ports:
            - 5432:5432

    web:
        build:
            context: .
            dockerfile: ./coffeshop_api/Dockerfile
        entrypoint: ./entrypoint.sh python manage.py runserver 0.0.0.0:8000
        environment:
            - DJANGO_SETTINGS_MODULE=core.settings.development
        volumes:
            - ./coffeshop_api:/code
        ports:
            - 8000:8000
        depends_on:
            - db

    bot:
        build:
            context: .
            dockerfile: ./telegram_bot/Dockerfile
        entrypoint: python main.py
        volumes:
            - ./telegram_bot:/code
        ports:
            - "8080:8080"

    redis:
        image: redis:latest
        env_file:
            - ./.env
        environment:
            - REDIS_PORT=${REDIS_PORT}

volumes:
    coffeshop_postgres_data:
